### ISSUE TITLE
ERROR: dependency 'Rcpp' is not available for package 'mongolitedt'

### ISSUE THREAD

**Issue by fracanz** [SymbolixAU/mongolitedt#7]
package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’

The downloaded binary packages are in
    C:\Users\Francesco\AppData\Local\Temp\RtmpSy5tBG\downloaded_packages
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Francesco/AppData/Local/Temp/RtmpSy5tBG/devtools30b8430b4296/SymbolixAU-mongolitedt-ce0d9a6"  \
  --library="C:/Users/Francesco/Documents/R/win-library/3.3" --install-tests 

ERROR: dependency 'Rcpp' is not available for package 'mongolitedt'
- removing 'C:/Users/Fra/Documents/R/win-library/3.3/mongolitedt'
  Error: Command failed (1)

**Comment by SymbolixAU** [comment]
I'm going to need a bit more information that just the error message...

what's your `sessionInfo()`?

**Comment by fracanz** [comment]
Sorry. Apparently it was indeeed a problem of session. I am not able to replicate this problem again. 
Thank you very much for your assistance.

**Comment by YujiZhang** [comment]
Had the same error. Restarted R and don't have it any more.
