### ISSUE TITLE
rbindlist with FILL = T

### ISSUE THREAD

**Issue by mmodin** [SymbolixAU/mongolitedt#8]
Hi

I'm trying to speed up my queries on a collection with where the documents contain different fields. e.g.

`find()`  would pad the missing fields with `<NA>` and produce something like this.
```
   name   id value
1:    A <NA>    10
2:    B    2    20
3:    C <NA>    30
```
whereas `finddt()` would give me an error:
```
data.table::rbindlist error:
Column 2 of item 1 is length 2, inconsistent with first column of that item which is length 1. rbind/rbindlist doesn't recycle as it already expects each item to be a uniform list, data.frame or data.table
```

Wouldn't it be possible to pass `data.table::rbindlist` with option `fill = TRUE` to solve this? If yes, is this available in `mongolitedt` somehow or is there any other way to speed up queries on such a collection?

Thanks

**Comment by SymbolixAU** [comment]
@MathiasModin  I have `fill = TRUE` as the default setting; see:

https://github.com/SymbolixAU/mongolitedt/blob/ce0d9a6757dc925bf8d8513e256cf93f09d8e7d1/R/try_rbind_page.R#L8

https://github.com/SymbolixAU/mongolitedt/blob/ce0d9a6757dc925bf8d8513e256cf93f09d8e7d1/R/mongo_stream_in_dt.R#L26

So I'm not sure if that is directly related to the issue you're seeing. Are you able to make a reproducible example?

---

Also, thanks for trying `mongolitedt` ; I haven't touched this project in a while but it would be good to get it back up and going.

**Comment by mmodin** [comment]
Thanks for replying. I'm afraid I can't create a reproducible example due to not having access to a local mongo server on this machine. However, I'll try to reproduce some data that would produce the same error.

```
library(mongolite)
library(mongolitedt)
library(jsonlite)

m <- mongo(collection = "x", db = "xx", url="mongodb://localhost")
bind_mongolitedt(m)
x <- m$find('{"headers.event_year": 2017}', fields = '{"_id": 0,"headers.event_year": 1, "body.Letter": 1, "body.Phonetic": 1}', limit = 4)

x
  event_year body.Letter body.Phonetic
1       2017           A         Alpha
2       2017           B         Bravo
3       2017        <NA>       Charlie
4       2017        <NA>         Delta
toJSON(x)

[{"headers":{"event_year":2017},"body":{"Letter":"A","Phonetic":"Alpha"}},{"headers":{"event_year":2017},"body":{"Letter":"B","Phonetic":"Bravo"}},{"headers":{"event_year":2017},"body":{"Phonetic":"Charlie"}},{"headers":{"event_year":2017},"body":{"Phonetic":"Delta"}}] 

m$finddt('{"headers.event_year": 2017}', fields = '{"_id": 0,"headers.event_year": 1, "body.Letter": 1, "body.Phonetic": 1}', limit = 4)

data.table::rbindlist error:
Column 2 of item 1 is length 0, inconsistent with first column of that item which is length 1. rbind/rbindlist doesn't recycle as it already expects each item to be a uniform list, data.frame or data.table
```

**Comment by SymbolixAU** [comment]
@MathiasModin 

`rbindlist` will only work if the data is 'tabular'; i.e. not nested lists / JSON, as in your example:

```
js <- '[{"headers":{"event_year":2017},"body":{"Letter":"A","Phonetic":"Alpha"}},{"headers":{"event_year":2017},"body":{"Letter":"B","Phonetic":"Bravo"}},{"headers":{"event_year":2017},"body":{"Phonetic":"Charlie"}},{"headers":{"event_year":2017},"body":{"Phonetic":"Delta"}}] '

df <- jsonlite::fromJSON(js)
data.table::rbindlist(df)
> Error in data.table::rbindlist(df) : 
  Item 2 has 2 columns, inconsistent with item 1 which has 1 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
```

You'll need to write an aggregation query that unwinds any arrays or extracts objects, and returns a single table.
