### ISSUE TITLE
Sort option in aggregatedt

### ISSUE THREAD

**Issue by buliin** [SymbolixAU/mongolitedt#9]
There is no option to `sort` the results of the query if we use `aggregatedt`. 
Defining `sort` in the `pipeline` attribute is skipped (doesn't work).  Is it possible to add `sort` option, just like in `finddt`?

**Comment by SymbolixAU** [comment]
Hi @buliin 
Do you have an example of it not working?

This works for me:

```
m <- mongo(db = "test", collection = "mtcars")
m$insert(mtcars)
bind_mongolitedt(m)
m$aggregatedt(pipeline = '[{"$match" : { "hp" : { "$gte" : 100} } }, {"$sort" : {"_row" : 1} } ]')
```

**Comment by buliin** [comment]
Ahh, good point. It was my mistake with the $project in query. 
What I did was:
`m$aggregatedt(pipeline = '[{"$match" : { "hp" : { "$gte" : 100} } }, {"$project" : {"test" : "$mpg" }}, {"$sort" : {"mpg" : 1} } ]')`

and it was not working. I should use instead:
`m$aggregatedt(pipeline = '[{"$match" : { "hp" : { "$gte" : 100} } }, {"$project" : {"test" : "$mpg" }}, {"$sort" : {"test" : 1} } ]')`
and everything is fine. 
Thanks for your help @SymbolixAU.
